@startuml activity
title Диаграмма деятельности для описания процесса обработки заказа системой

start

repeat
    :Пользователь нажимает\n"Оформить заказ";
backward:Сообщить пользователю;
repeat while (Корзина пустая?) is (да) not (нет)

if (Нужно дополнить заказ деталями?) then (да)
    :Заполнить детали заказа;
endif

:Сфомировать чек на оплату;
:Отправить чек на оплату пользователю;

if (В течение 15 минут заказ оплачен?) then (да)
    :Отправить сообщение\nпользователю "Заказ оформлен";
    fork
    :Отправить состав заказа\nв ресторан на выполнение;
    if (В течение 60 минут\nполучен ответ о\nготовности заказа?) then (да)
        :Пометить заказ\nприготовленным;
    else (нет)
        fork
        :Сообщить пользователю\nоб отмене;
        :Вернуть деньги;
        :Составить дисциплинарную\nзаписку на ресторан;
        forkagain
        :Сообщить курьеру об отмене;
        endfork
        stop
    endif
    fork again
    repeat
        :Найти ближайшего курьера;
        :Рассчитать маршрут и детали\nзаказа под этого курьера;
        :Отправить предложение курьеру;
    repeat while (Курьер не согласен?)
    :Прикрепить заказ к выбранному курьеру;
    endfork
    if (Курьер забрал заказ в течение\nn минут (время пути до ресторана + 15 минут)\nпосле смены статуса заказа на приготовленный?) then (да)
        :Пометить заказ\nвзятым из ресторана;
        if (Заказ был доставлен в течение n минут\n(время до адреса пользователя + 15 минут)?) then (да)
            :Пометить заказ выполненным;
        else (Нет)
            :Сообщить пользователю\nоб отмене;
            :Вернуть деньги;
            :Составить дисциплинарную\nзаписку на курьера;
        endif
    else (нет) 
        :Сообщить пользователю\nоб отмене;
        :Вернуть деньги;
        :Составить дисциплинарную\nзаписку на курьера;
    endif
else (нет) 
    :Отменить заказ;
    stop
endif

stop

@enduml 